#python replot_from_log.py "D:\IITD\MTP 2\Results\log_ablation_CIFAR10_NON_IID_20240409_120000.txt"





import re
import os
import argparse
import config
import plotter

def parse_log_file(filepath):
    """
    Parses a log file generated by main.py and extracts the accuracy and loss histories 
    for each experiment run, returning them in a format compatible with plotter.py.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split the content by the header printed at the start of each experiment
    exp_chunks = re.split(r'------------------------------- Starting Experiment: ', content)
    
    if len(exp_chunks) <= 1:
        print("No experiments found or invalid log format.")
        return []
    
    all_results = []
    
    # A professional, color-blind friendly aesthetic palette 
    
    scenario_colors = {
        'no attack': '#2ecc71',
        'sign flip': '#e74c3c',
        'label flip': '#9b59b6',
        'ipm': '#e67e22',
        'volume spam': '#1abc9c',
        'alie': '#c0392b',
        'sybil': '#2c3e50',
        'pure additive noise': '#bdc3c7',
        'additive noise': '#3498db',
        'catastrophic noise': '#e056fd'
    }

    color_idx = 0
    
    for chunk in exp_chunks[1:]:  # Skip index 0 as it contains metadata/imports prior to the first experiment
        lines = chunk.split('\n')
        # Extract the label, which ends at the dashes
        label = lines[0].split(' -------------------------------')[0].strip()
        
        accuracy_history = []
        loss_history = []
        duration = 0.0
        
        for line in lines:
            # Match the standard evaluation line
            # Example: > EVALUATION: Global Model Loss: 0.9007, Accuracy: 70.05%
            eval_match = re.search(r'EVALUATION: Global Model Loss: ([\d\.]+), Accuracy: ([\d\.]+)%', line)
            if eval_match:
                loss = float(eval_match.group(1))
                acc = float(eval_match.group(2))
                loss_history.append(loss)
                accuracy_history.append(acc)
            
            # Match the total duration line
            # Example: > Total Duration: 14.48s
            dur_match = re.search(r'> Total Duration: ([\d\.]+)s', line)
            if dur_match:
                duration = float(dur_match.group(1))
        
        # Deduce original plotting metadata to construct original filenames
        lbl_lower = label.lower()
        if "aegis" in lbl_lower: agg_name = "aegis"
        elif "krum" in lbl_lower: agg_name = "krum"
        elif "fedavg" in lbl_lower: agg_name = "fedavg"
        elif "bulyan" in lbl_lower: agg_name = "bulyan"
        elif "foolsgold" in lbl_lower: agg_name = "foolsgold"
        elif "cwmed" in lbl_lower: agg_name = "cwmed"
        else: agg_name = "unknown"
        
        if "label_flip" in lbl_lower: atk_type = "label_flip"
        elif "sign_flip" in lbl_lower: atk_type = "sign_flip"
        elif "ipm" in lbl_lower: atk_type = "ipm"
        elif "alie" in lbl_lower: atk_type = "alie"
        elif "sybil" in lbl_lower: atk_type = "sybil"
        elif "volume_spam" in lbl_lower: atk_type = "volume_spam"
        elif "noise" in lbl_lower: atk_type = "additive_noise"
        else: atk_type = "none"

        if len(accuracy_history) > 0:
            result = {
                'label': label,
                'color': next((c for k, c in scenario_colors.items() if k in label.lower()), '#000000'),
                'marker': 'o',
                'linestyle': 'solid',
                'history': accuracy_history,
                'loss_history': loss_history,
                
                # Metrics required for the bar chart
                'best_accuracy': max(accuracy_history) if accuracy_history else 0.0,
                'best_loss': min(loss_history) if loss_history else 0.0,
                'latest_accuracy': accuracy_history[-1] if accuracy_history else 0.0,
                'duration': duration,
                
                # Metadata required for naming saved files in plotter parameter extraction
                'aggregator_name': agg_name,
                'attack_type': atk_type,
                
                # Dummy placeholders to prevent the plotter from throwing missing key errors
                'attack_intensity': [],
                'participant_counts': [],
                'agg_time_history': [],
                'adaptive_k_history': [],
                'tp_history': [],
                'fp_history': [],
                'fn_history': [],
                'approval_rate_history': [],
                'detection_rate_history': [],
                'precision_history': []
            }
            all_results.append(result)
            color_idx += 1
            
    return all_results


def main():
    parser = argparse.ArgumentParser(description='Replot FL Experiments from a log file into High Resolution.')
    parser.add_argument('logfile', type=str, help='Absolute or relative path to the log_...txt file.')
    args = parser.parse_args()
    
    if not os.path.exists(args.logfile):
        print(f"Error: Log file not found at '{args.logfile}'")
        return
        
    print(f"Parsing log file: {args.logfile}")
    all_results = parse_log_file(args.logfile)
    
    if not all_results:
        print("Failed to extract any results from the log file.")
        return
        
    print(f"Extracted {len(all_results)} experiment(s) from log.")
    for r in all_results:
        print(f" - {r['label']}: {len(r['history'])} rounds found.")
        
    # --- Enforcement of High Quality Plot Settings ---
    config.SAVE_DPI = 600
    config.IEEE_STYLE_ENABLED = False
    config.RESULTS_DIR = os.path.dirname(os.path.abspath(args.logfile))
    
    # Optionally: Disable gradient scatters during replotting just to be safe
    config.VISUALIZE_GRADIENTS = False
    
    print("\nRe-rendering plots via plotter.py...")
    # Generate the line and bar plots based on parsed log file data
    plotter.plot_results(all_results, config)
    plotter.plot_final_summary_bars(all_results, config)
    
    print("\n[Done] High-resolution replotting complete! Check your Results directory.")


if __name__ == '__main__':
    main()
